name: deploy
on:
  push: { branches: ["develop"] }
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    concurrency: { group: deploy-frontend, cancel-in-progress: true }
    steps:
      - run: bash ~/app/matetrip-frontend/deploy.sh
